//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9164
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   終了します。よろしいですか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDP_ASK_TO_EXIT {
            get {
                return ResourceManager.GetString("AFX_IDP_ASK_TO_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %1 への変更を保存しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDP_ASK_TO_SAVE {
            get {
                return ResourceManager.GetString("AFX_IDP_ASK_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル (*.*) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_ALLFILTER {
            get {
                return ResourceManager.GetString("AFX_IDS_ALLFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_IDLEMESSAGE {
            get {
                return ResourceManager.GetString("AFX_IDS_IDLEMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_OBJ_TITLE_INPLACE {
            get {
                return ResourceManager.GetString("AFX_IDS_OBJ_TITLE_INPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ページ(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_ONEPAGE {
            get {
                return ResourceManager.GetString("AFX_IDS_ONEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ %u\nページ %u-%u\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_PREVIEWPAGEDESC {
            get {
                return ResourceManager.GetString("AFX_IDS_PREVIEWPAGEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ %u に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_PRINTPAGENUM {
            get {
                return ResourceManager.GetString("AFX_IDS_PRINTPAGENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 ページ(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_TWOPAGE {
            get {
                return ResourceManager.GetString("AFX_IDS_TWOPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無題 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AFX_IDS_UNTITLED {
            get {
                return ResourceManager.GetString("AFX_IDS_UNTITLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム情報、バージョン、著作権を表示します。\nバージョン情報\nﾍﾙﾌﾟ\n著作権情報を表示しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_APP_ABOUT {
            get {
                return ResourceManager.GetString("ID_APP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションを終了し、ドキュメントの保存を指示\n終了\n終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_APP_EXIT {
            get {
                return ResourceManager.GetString("ID_APP_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲を消去\n消去\n消去\n消去しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_CLEAR {
            get {
                return ResourceManager.GetString("ID_EDIT_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて消去\nすべて消去\n全消\nすべて消去しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_CLEAR_ALL {
            get {
                return ResourceManager.GetString("ID_EDIT_CLEAR_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲をコピーしてクリップボードに保存\nコピー\nｺﾋﾟｰ\n選択範囲をクリップボードへコピーしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_COPY {
            get {
                return ResourceManager.GetString("ID_EDIT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択範囲を切り取ってクリップボードに保存\n切り取り\n切取\n選択範囲をクリップボードへ移動しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_CUT {
            get {
                return ResourceManager.GetString("ID_EDIT_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した文字列の検索\n検索\n検索\n検索文字列を指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_FIND {
            get {
                return ResourceManager.GetString("ID_EDIT_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリップボードの内容を貼り付け\n貼り付け\n貼付\nクリップボードから貼り付けました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_PASTE {
            get {
                return ResourceManager.GetString("ID_EDIT_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取り消した操作をやり直す\nやり直す\n直す\n変更を取り消しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_REDO {
            get {
                return ResourceManager.GetString("ID_EDIT_REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   直前に行った動作を繰り返す\n繰り返し\n繰返\n次を検索しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_REPEAT {
            get {
                return ResourceManager.GetString("ID_EDIT_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定した文字列を他の文字列で置換\n置換\n置換\n置換文字列を指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_REPLACE {
            get {
                return ResourceManager.GetString("ID_EDIT_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル内のすべてを選択\nすべて選択\n全選\nすべて選択しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_SELECT_ALL {
            get {
                return ResourceManager.GetString("ID_EDIT_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   直前に行った動作を元に戻す\n元に戻す\n戻す\n元に戻しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_EDIT_UNDO {
            get {
                return ResourceManager.GetString("ID_EDIT_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業中のドキュメントを閉じる\n閉じる\n閉じ\nドキュメントを閉じました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_CLOSE {
            get {
                return ResourceManager.GetString("ID_FILE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいドキュメントを作成\n新規作成\n新規\n新規作成しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_NEW {
            get {
                return ResourceManager.GetString("ID_FILE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既存のドキュメントを開く\n開く\n開く\nドキュメントを開きました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_OPEN {
            get {
                return ResourceManager.GetString("ID_FILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷オプションの変更\nページ レイアウトの設定\n頁設\nページ レイアウトを設定しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_PAGE_SETUP {
            get {
                return ResourceManager.GetString("ID_FILE_PAGE_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業中のドキュメントを印刷\n印刷\n印刷\n印刷しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_PRINT {
            get {
                return ResourceManager.GetString("ID_FILE_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業中のドキュメントを現在のオプションで印刷\nクイック印刷\n印刷\n印刷しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_PRINT_DIRECT {
            get {
                return ResourceManager.GetString("ID_FILE_PRINT_DIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷イメージを表示\n印刷プレビュー\nプレ\n印刷プレビューしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_PRINT_PREVIEW {
            get {
                return ResourceManager.GetString("ID_FILE_PRINT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリンターおよび印刷オプションの変更\n印刷設定\n設定\n印刷設定しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_PRINT_SETUP {
            get {
                return ResourceManager.GetString("ID_FILE_PRINT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業中のドキュメントを上書きして保存\n保存\n保存\nドキュメントを保存しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_SAVE {
            get {
                return ResourceManager.GetString("ID_FILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業中のドキュメントを新しい名前で保存\n名前をつけて保存\n名付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_FILE_SAVE_AS {
            get {
                return ResourceManager.GetString("ID_FILE_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_CAPS {
            get {
                return ResourceManager.GetString("ID_INDICATOR_CAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列:{0,5} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_COL {
            get {
                return ResourceManager.GetString("ID_INDICATOR_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_DATE {
            get {
                return ResourceManager.GetString("ID_INDICATOR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_MODIFY {
            get {
                return ResourceManager.GetString("ID_INDICATOR_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NUM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_NUM {
            get {
                return ResourceManager.GetString("ID_INDICATOR_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行:{0,5} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_ROW {
            get {
                return ResourceManager.GetString("ID_INDICATOR_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SCRL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_SCRL {
            get {
                return ResourceManager.GetString("ID_INDICATOR_SCRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HH mm\nHH:mm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_INDICATOR_TIME {
            get {
                return ResourceManager.GetString("ID_INDICATOR_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷プレビューを閉じる\n閉じる\n閉じる(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_CLOSE {
            get {
                return ResourceManager.GetString("ID_PREVIEW_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次のページ\n次のページ\n次へ(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_NEXT {
            get {
                return ResourceManager.GetString("ID_PREVIEW_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 ページ表示/2 ページ表示の切り替え\n切り替え\n2ページ(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_ONEPAGE {
            get {
                return ResourceManager.GetString("ID_PREVIEW_ONEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前のページ\n前のページ\n前へ(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_PREV {
            get {
                return ResourceManager.GetString("ID_PREVIEW_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文書の印刷\n印刷\n印刷(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_PRINT {
            get {
                return ResourceManager.GetString("ID_PREVIEW_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定\n設定\n設定(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_SETUP {
            get {
                return ResourceManager.GetString("ID_PREVIEW_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大\n拡大\n拡大(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_ZOOMIN {
            get {
                return ResourceManager.GetString("ID_PREVIEW_ZOOMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縮小\n縮小\n縮小(&amp;R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_PREVIEW_ZOOMOUT {
            get {
                return ResourceManager.GetString("ID_PREVIEW_ZOOMOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ内の各オブジェクトの詳細情報を表示します。\n詳細\n詳細\n詳細表示へ変更しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_VIEW_DETAILS {
            get {
                return ResourceManager.GetString("ID_VIEW_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オブジェクトを大きいアイコンで表示します。\n大きいアイコン\n大\n大きいアイコン表示へ変更しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_VIEW_LARGEICON {
            get {
                return ResourceManager.GetString("ID_VIEW_LARGEICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オブジェクトを一覧表示します。\n一覧\n一覧\n一覧表示へ変更しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_VIEW_LIST {
            get {
                return ResourceManager.GetString("ID_VIEW_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オブジェクトを小さいアイコンで表示します。\n小さいアイコン\n小\n小さいアイコン表示へ変更しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_VIEW_SMALLICON {
            get {
                return ResourceManager.GetString("ID_VIEW_SMALLICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス バーの表示/非表示\nステータス バーの表示切り替え\nステータス バーの表示を変更しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_VIEW_STATUS_BAR {
            get {
                return ResourceManager.GetString("ID_VIEW_STATUS_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール バーの表示/非表示\nステータス バーの表示切り替え\nツール バーの表示を変更しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ID_VIEW_TOOLBAR {
            get {
                return ResourceManager.GetString("ID_VIEW_TOOLBAR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap IDB_APP_ABOUT {
            get {
                object obj = ResourceManager.GetObject("IDB_APP_ABOUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_APP_EXIT {
            get {
                object obj = ResourceManager.GetObject("IDB_APP_EXIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_EDIT_COPY {
            get {
                object obj = ResourceManager.GetObject("IDB_EDIT_COPY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_EDIT_CUT {
            get {
                object obj = ResourceManager.GetObject("IDB_EDIT_CUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_EDIT_PASTE {
            get {
                object obj = ResourceManager.GetObject("IDB_EDIT_PASTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_FILE_NEW {
            get {
                object obj = ResourceManager.GetObject("IDB_FILE_NEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_FILE_OPEN {
            get {
                object obj = ResourceManager.GetObject("IDB_FILE_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_FILE_PRINT {
            get {
                object obj = ResourceManager.GetObject("IDB_FILE_PRINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_FILE_SAVE {
            get {
                object obj = ResourceManager.GetObject("IDB_FILE_SAVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_CLOSE {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_CLOSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_NEXT {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_NEXT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_ONEPAGE {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_ONEPAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_PREV {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_PREV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_PRINT {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_PRINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_SETUP {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_SETUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_ZOOMIN {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_ZOOMIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_PREVIEW_ZOOMOUT {
            get {
                object obj = ResourceManager.GetObject("IDB_PREVIEW_ZOOMOUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_VIEW_DETAILS {
            get {
                object obj = ResourceManager.GetObject("IDB_VIEW_DETAILS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_VIEW_LARGEICON {
            get {
                object obj = ResourceManager.GetObject("IDB_VIEW_LARGEICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_VIEW_LIST {
            get {
                object obj = ResourceManager.GetObject("IDB_VIEW_LIST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_VIEW_SMALLICON {
            get {
                object obj = ResourceManager.GetObject("IDB_VIEW_SMALLICON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IDB_VIEW_STRIPED {
            get {
                object obj = ResourceManager.GetObject("IDB_VIEW_STRIPED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   バージョン情報(&amp;A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_APP_ABOUT {
            get {
                return ResourceManager.GetString("IDM_APP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_APP_EXIT {
            get {
                return ResourceManager.GetString("IDM_APP_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(&amp;E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT {
            get {
                return ResourceManager.GetString("IDM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除(&amp;D)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_CLEAR {
            get {
                return ResourceManager.GetString("IDM_EDIT_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_COPY {
            get {
                return ResourceManager.GetString("IDM_EDIT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_CUT {
            get {
                return ResourceManager.GetString("IDM_EDIT_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索(&amp;F)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_FIND {
            get {
                return ResourceManager.GetString("IDM_EDIT_FIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_PASTE {
            get {
                return ResourceManager.GetString("IDM_EDIT_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_REPEAT {
            get {
                return ResourceManager.GetString("IDM_EDIT_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   置換(&amp;N)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_REPLACE {
            get {
                return ResourceManager.GetString("IDM_EDIT_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_SELECT_ALL {
            get {
                return ResourceManager.GetString("IDM_EDIT_SELECT_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す(&amp;U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_EDIT_UNDO {
            get {
                return ResourceManager.GetString("IDM_EDIT_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE {
            get {
                return ResourceManager.GetString("IDM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_NEW {
            get {
                return ResourceManager.GetString("IDM_FILE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(&amp;O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_OPEN {
            get {
                return ResourceManager.GetString("IDM_FILE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ設定(&amp;T)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_PAGE_SETUP {
            get {
                return ResourceManager.GetString("IDM_FILE_PAGE_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷(&amp;P)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_PRINT {
            get {
                return ResourceManager.GetString("IDM_FILE_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷プレビュー(&amp;V)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_PRINT_PREVIEW {
            get {
                return ResourceManager.GetString("IDM_FILE_PRINT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷設定(&amp;T)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_PRINT_SETUP {
            get {
                return ResourceManager.GetString("IDM_FILE_PRINT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_SAVE {
            get {
                return ResourceManager.GetString("IDM_FILE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前をつけて保存(&amp;A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_SAVE_AS {
            get {
                return ResourceManager.GetString("IDM_FILE_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信(&amp;D)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_FILE_SEND_MAIL {
            get {
                return ResourceManager.GetString("IDM_FILE_SEND_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_HELP {
            get {
                return ResourceManager.GetString("IDM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目次(&amp;C)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_HELP_CONTENTS {
            get {
                return ResourceManager.GetString("IDM_HELP_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ検索(&amp;S)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_HELP_FINDER {
            get {
                return ResourceManager.GetString("IDM_HELP_FINDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索引(&amp;I)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_HELP_INDEX {
            get {
                return ResourceManager.GetString("IDM_HELP_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(&amp;M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_OLE_EDIT_PROPERTIES {
            get {
                return ResourceManager.GetString("IDM_OLE_EDIT_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   挿入(&amp;I)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_OLE_INSERT_NEW {
            get {
                return ResourceManager.GetString("IDM_OLE_INSERT_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示(&amp;V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_VIEW {
            get {
                return ResourceManager.GetString("IDM_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_VIEW_DETAILS {
            get {
                return ResourceManager.GetString("IDM_VIEW_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大きいアイコン(&amp;G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_VIEW_LARGEICON {
            get {
                return ResourceManager.GetString("IDM_VIEW_LARGEICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧(&amp;L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_VIEW_LIST {
            get {
                return ResourceManager.GetString("IDM_VIEW_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小さいアイコン(&amp;M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_VIEW_SMALLICON {
            get {
                return ResourceManager.GetString("IDM_VIEW_SMALLICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス バー(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_VIEW_STATUS_BAR {
            get {
                return ResourceManager.GetString("IDM_VIEW_STATUS_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール バー(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDM_VIEW_TOOLBAR {
            get {
                return ResourceManager.GetString("IDM_VIEW_TOOLBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDP_AFXBARRES_TEXT_IS_REQUIRED {
            get {
                return ResourceManager.GetString("IDP_AFXBARRES_TEXT_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_AFXBARRES_ABORT {
            get {
                return ResourceManager.GetString("IDS_AFXBARRES_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_AFXBARRES_CANCEL {
            get {
                return ResourceManager.GetString("IDS_AFXBARRES_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel 8.0;HDR=YES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_CONNECTION_EXTENDED_PROPERTIES {
            get {
                return ResourceManager.GetString("IDS_CONNECTION_EXTENDED_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft.Jet.OLEDB.4.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_CONNECTION_STRING_32 {
            get {
                return ResourceManager.GetString("IDS_CONNECTION_STRING_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft.ACE.OLEDB.12.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_CONNECTION_STRING_64 {
            get {
                return ResourceManager.GetString("IDS_CONNECTION_STRING_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_EDIT_MENU {
            get {
                return ResourceManager.GetString("IDS_EDIT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C:\Windows\Help\mui\0411\mmc.CHM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_HELP_FILENAME {
            get {
                return ResourceManager.GetString("IDS_HELP_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (不明)\n重大\n確認\n警告\n情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_MESSAGE_TITLES {
            get {
                return ResourceManager.GetString("IDS_MESSAGE_TITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select * from [Sheet1$] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDS_SQL_SELECT {
            get {
                return ResourceManager.GetString("IDS_SQL_SELECT", resourceCulture);
            }
        }
    }
}
